import Head from "next/head";
import Image from "next/image";
import Logo from "/images/logo.jpg";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Layout from '../layout/layout'

const LogoNext = (props) => {
  return (
    <Image 
      src="/images/logo/Nextjs-logo.svg"
      alt="logo next"
      width={80}
      height={60}
    />
  )
}

const inter = Inter({ subsets: ["latin"] });


export default function Home() {
  return (
    <>
      <Head>
        <title>Doctor Demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
        <link rel="icon" href="/images/logo.jpg" />
      </Head>
     <Layout>
      <div className="px-10 flex space-x-4">
        <h1>Home </h1>
        <span><LogoNext/></span>
      </div>
      
     </Layout>
    </>
  );
}
