import Head from "next/head";

export default function User() {
  return (
    <>
      <Head>
        <title>User detail</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.jpg" />
      </Head>
      <h1>User page</h1>
    </>
  );
}
